
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "150"
	#Energy per operation tick (Joules).
	osmiumCompressor = "300"
	#Energy per operation tick (Joules).
	combiner = "150"
	#Energy per operation tick (Joules).
	crusher = "150"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "150"
	#Energy per operation tick (Joules).
	purificationChamber = "600"
	#Energy per operation tick (Joules).
	energizedSmelter = "150"
	#Energy per operation tick (Joules).
	digitalMiner = "3000"
	#Energy per operation tick (Joules).
	electricPump = "300"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "3072000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "150"
	#Energy per operation tick (Joules).
	oxidationChamber = "600"
	#Energy per operation tick (Joules).
	chemicalInfuser = "600"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "1200"
	#Energy per operation tick (Joules).
	precisionSawmill = "150"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "1200"
	#Energy per operation tick (Joules).
	chemicalWasher = "600"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "1200"
	#Energy per operation tick (Joules).
	seismicVibrator = "150"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "15"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "300"
	#Energy per operation tick (Joules).
	laser = "30000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "300"
	#Energy per operation tick (Joules).
	modificationStation = "300"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "600"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "600"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "300000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "600"
	#Energy per operation tick (Joules).
	pigmentMixer = "600"
	#Energy per operation tick (Joules).
	paintingMachine = "300"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "15000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "3000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "30"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "30000"

